version: '2.0'

services:

  api:
    container_name: nest_api
    build: .
    ports:
      - "3000:3000" # "${API_PORT}:${API_PORT}" para ver as variáveis no '.env'
    volumes:
      - .:/home/api  # Apenas para fins de desenvolvimento

  database:
    image: postgres:13
    container_name: nest_db
    # restart: always
    environment:
      POSTGRES_DB: nest_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"